GPT_SUPPORTED_MODELS = [
    "gpt-4o",
    "gpt-4o-mini",
    "gpt-4.1",
    "gpt-4.1-mini"
]


def gpt_generate(api_key: str, model: str, prompt: str, system_prompt: str):
    """
    Generate a response using a GPT language model.

    This function calls the OpenAI GPT API to generate a response based on
    the given user prompt and system prompt.

    Args:
        api_key (str): API key for authenticating with the OpenAI API.
        model (str): Name of the GPT model to use (must be in GPT_SUPPORTED_MODELS).
        prompt (str): The user input or query to send to the model.
        system_prompt (str): System-level instructions to guide model behavior.

    Returns:
        dict: A dictionary containing:
            - 'provider' (str): The model provider, always "openai".
            - 'model' (str): The model used.
            - 'response' (str): The text response generated by the model.

    Raises:
        ImportError: If `openai` library is not installed.
        Exception: If the API call fails for any reason.
    """

    try:
        from openai import OpenAI
    except ImportError:
        raise ImportError("Install: pip install openai")

    client = OpenAI(api_key=api_key)

    response = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": prompt}
        ]
    )

    return {
        "provider": "openai",
        "model": model,
        "response": response.choices[0].message.content
    }
